### ISSUE TITLE
AttributeError: 'ReLU6' object has no attribute 'dim'

### ISSUE THREAD

**Issue by hhlgithub** [Randl/MobileNetV2-pytorch#1]
After I copy your codes and add my my test codes, as follows: 

`model = MobileNet2(in_channels=6,num_classes=100)`
`print (model)`
`x = torch.autograd.Variable(torch.randn(20, 6, 224, 224))`
`print (model(x))`

I encounter such errors  **AttributeError: 'ReLU6' object has no attribute 'dim'**

**Comment by Randl** [comment]
Thanks. 
Fixed in https://github.com/Randl/MobileNetV2-pytorch/commit/e77ad8a5db1db53bda2ede0b65574d249796bf4f
