### ISSUE TITLE
Evaluate you model failed

### ISSUE THREAD

**Issue by xiaozhuka** [Randl/MobileNetV2-pytorch#11]
**Hi @Randl ,Thanks for your work.
When I evaluate the model in results folder using following command:**
python imagenet.py --dataroot ~/data/ImageNet/ -e --resume results/mobilenet_v2_1.0_224/model_best.pth.tar

**Output is this:**
......
number of parameters: 3505960
FLOPs: 312339328
=> loading checkpoint 'results/mobilenet_v2_1.0_224/model_best.pth.tar'
Traceback (most recent call last):
  File "imagenet.py", line 160, in <module>
    main()
  File "imagenet.py", line 147, in main
    model.load_state_dict(checkpoint['state_dict'])
  File "/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MobileNet2:
	Missing key(s) in state_dict: "conv1.weight", "bn1.running_var", "bn1.bias", "bn1.weight", "bn1.running_mean", "bottlenecks.Bottlenecks_0.LinearBottleneck0_0.conv1.weight", "bottlenecks.Bottlenecks_0.LinearBottleneck0_0.bn1.running_var", "bottlenecks.Bottlenecks_0.LinearBottleneck0_0.bn1.bias",..........

**Please tell me what's going wrong?Thanks.**

**Comment by xiaozhuka** [comment]
in cpu mode got above error. 
set --gpus get accuracy: 

number of parameters: 3505960
FLOPs: 312339328
=> loading checkpoint 'results/mobilenet_v2_1.0_224/model_best.pth.tar'
=> loaded checkpoint 'results/mobilenet_v2_1.0_224/model_best.pth.tar' (epoch 401)
100%|██████████| 782/782 [10:13<00:00,  2.01it/s]
Test set: Average loss: 1.1362, Top1: 36043/50000 (72.09%), Top5: 45257/50000 (90.51%)

**A little different with readme.md: top1 72.10%, top5 90.48%**

number of parameters: 1968968
FLOPs: 50542400
=> loading checkpoint 'results/mobilenet_v2_0.5_160/model_best.pth.tar'
=> loaded checkpoint 'results/mobilenet_v2_0.5_160/model_best.pth.tar' (epoch 365)
100%|██████████| 782/782 [10:29<00:00,  2.14it/s]

Test set: Average loss: 1.6696, Top1: 30322/50000 (60.64%), Top5: 41427/50000 (82.85%)
**A little different with readme.md: top1 60.61%, top5 82.87%**

**Comment by chaotianjiao** [comment]
@xiaozhuka Hi, I have the same problem,Have you solved it?

> **Hi @Randl ,Thanks for your work. When I evaluate the model in results folder using following command:**
> python imagenet.py --dataroot ~/data/ImageNet/ -e --resume results/mobilenet_v2_1.0_224/model_best.pth.tar
> 
> **Output is this:**
> ......
> number of parameters: 3505960
> FLOPs: 312339328
> => loading checkpoint 'results/mobilenet_v2_1.0_224/model_best.pth.tar'
> Traceback (most recent call last):
> File "imagenet.py", line 160, in
> main()
> File "imagenet.py", line 147, in main
> model.load_state_dict(checkpoint['state_dict'])
> File "/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for MobileNet2:
> Missing key(s) in state_dict: "conv1.weight", "bn1.running_var", "bn1.bias", "bn1.weight", "bn1.running_mean", "bottlenecks.Bottlenecks_0.LinearBottleneck0_0.conv1.weight", "bottlenecks.Bottlenecks_0.LinearBottleneck0_0.bn1.running_var", "bottlenecks.Bottlenecks_0.LinearBottleneck0_0.bn1.bias",..........
> 
> **Please tell me what's going wrong?Thanks.**
