### ISSUE TITLE
RuntimeError: Output size is too small

### ISSUE THREAD

**Issue by hhlgithub** [Randl/MobileNetV2-pytorch#2]
Thank you very much for modifying last bugs. It has benefited me a lot. But when I input following codes:
`model = MobileNet2(in_channels=2, num_classes=10)`
`print (model)`
`x = torch.autograd.Variable(torch.randn(1, 2, 20, 224))`
`print(model(x))`
I encounter such errors : **RuntimeError: Given input size: (1280x1x7). Calculated output size: (1280x0x1). Output size is too small at /opt/conda/conda-bld/pytorch-cpu_1518281700712/work/torch/lib/THNN/generic/SpatialAveragePooling.c:64**

**Comment by Randl** [comment]
Input size is assumed to be 224x224
