### ISSUE TITLE
pytorch 0.4.0

### ISSUE THREAD

**Issue by fangmingbnu** [Randl/MobileNetV2-pytorch#4]
I am using pytorch 0.3.1 for some reason. When I run your model,  "model.py" line 112 has a error which is ' AttributeError: 'module' object has no attribute 'kaiming_normal_'. If I use pytorch 0.4.0, the error will disappear. Could you please help me about this? Whether I could modify the model.py to avoid such error using pytorch 0.3.1.

**Comment by Randl** [comment]
You just need to remove last underscore. There are other breaking changes however

**Comment by fangmingbnu** [comment]
Could you please specify which underscore? Is that would hurt the performance of this model? Thanks!

**Comment by Randl** [comment]
[`kaiming_normal`](https://pytorch.org/docs/0.3.0/nn.html#torch.nn.init.kaiming_normal) instead of [`kaiming_normal_`](https://pytorch.org/docs/stable/nn.html#torch.nn.init.kaiming_normal_)
