### ISSUE TITLE
What is the training command for reproducing your results? 

### ISSUE THREAD

**Issue by AIROBOTAI** [Randl/MobileNetV2-pytorch#7]
Hi, thanks a lot for sharing your codes! One question, could the amazing results (mobilenetv2 top1 acc. 72.1%) be reproduced by simply running the following command?
`python imagenet.py --dataroot "/path/to/imagenet/"`

Or is there any other hyperparameters I should set for getting the best result? How many gpus shoud be used? Thanks a lot!

**Comment by Randl** [comment]
If you take a look at https://github.com/Randl/MobileNetV2-pytorch/blob/master/results/mobilenet_v2_1.0_224/params.txt
you ll see the precise parameters used for training. See also https://github.com/Randl/MobileNetV2-pytorch/issues/6

**Comment by AIROBOTAI** [comment]
Sorry.. I didn't check previous issues. Thanks a lot for your answer!
